openapi: 3.0.0
info:
  title: API BuilderGPT
  version: 1.0.0
servers:
  - url: https://buildergpt-production.up.railway.app
paths:
  /action:
    post:
      summary: Action principale de BuilderGPT
      operationId: actionBuilderGPT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                intention:
                  type: string
                contenu:
                  type: string
              required:
                - intention
                - contenu
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
