openapi: 3.1.0
info:
  title: BuilderGPT API
  version: 1.0.0
servers:
  - url: https://buildergpt-production.up.railway.app

paths:
  /analyse:
    post:
      summary: Analyse d’intention de création GPT
      operationId: analyserIntention
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                intention:
                  type: string
              required: [intention]
      responses:
        "200":
          description: Résultat de l’analyse

  /memoire-chat:
    post:
      summary: Enregistre un souvenir texte dans la mémoire
      operationId: enregistrerMemoireChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contenu:
                  type: string
              required: [contenu]
      responses:
        "200":
          description: Souvenir enregistré
