openapi: 3.1.0
info:
  title: BuilderGPT API
  version: 1.0.0
servers:
  - url: https://buildergpt-production.up.railway.app

paths:
  /analyse:
    post:
      summary: Analyse d’intention de création GPT
      operationId: analyserIntention
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                intention:
                  type: string
              required: [intention]
      responses:
        "200":
          description: Résultat de l’analyse
          
  /memoire-chat:
    post:
      summary: Enregistre un chat complet dans la mémoire de BuilderGPT
      operationId: enregistrerChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titre:
                  type: string
                résumé:
                  type: string
                contenu:
                  type: string
              required: [titre, résumé, contenu]
      responses:
        "200":
          description: Chat enregistré

