openapi: 3.0.0
info:
  title: BuilderGPT – Actions internes
  version: 1.1.0
paths:
  /analyse:
    post:
      summary: Analyse l’intention utilisateur
      operationId: analyseIntention
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                intention:
                  type: string
      responses:
        '200':
          description: Analyse complète
          content:
            application/json:
              schema:
                type: object
                properties:
                  plan:
                    type: string

  /genere-bundle:
    post:
      summary: Génère tous les fichiers d’un GPT métier
      operationId: genereBundle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom_agent:
                  type: string
                intention:
                  type: string
      responses:
        '200':
          description: Pack généré
          content:
            application/json:
              schema:
                type: object
                properties:
                  zip_link:
                    type: string

  /log-memoire:
    post:
      summary: Enregistre la génération dans la mémoire JSON
      operationId: logMemoire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom_agent:
                  type: string
                intention:
                  type: string
                date:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                lien_zip:
                  type: string
      responses:
        '200':
          description: Mémoire mise à jour
